### ISSUE TITLE
fetch latest OpenEMR from github

### ISSUE THREAD

**Issue by ibakayoko** [QuantumObject/docker-openemr#5]
Can you please update https://github.com/QuantumObject/docker-openemr/blob/master/pre-conf.sh

To fetch the zip from github https://github.com/openemr/openemr/archive/master.zip

Nice work

**Comment by angelrr7702** [comment]
done, but sill need to build it at docker ... need to build image baseimage first and them this build , I will update when done build ..

**Comment by angelrr7702** [comment]
Build done. please let me know if any problem with it .. at the moment working and unable to test it.

**Comment by ibakayoko** [comment]
Hello,
I was able to to pull the latest images : 
latest: Pulling from quantumobject/docker-baseimage
latest: Pulling from quantumobject/docker-openemr

After running docker run -d -p 443 --link mysql5.5:db quantumobject/docker-openemr

And going to the link to start the install, we have some permissions issues on openemr files. (see attached file)

![screen shot 2015-12-29 at 9 18 23 am](https://cloud.githubusercontent.com/assets/3247064/12035733/43022a66-ae0d-11e5-8db9-8e64a9c9e619.png)

**Comment by angelrr7702** [comment]
Done. I change some ownership of file to apache2 www-data and it fixed . I already test installation and worked fine.   let me know of any other problem with it .  

sincerely
Angel Rodriguez
